/** GENERATED by prototype/scripts/export_effects.py — do not edit. */
export type EffectKind = "attack" | "heal" | "shield" | "buff" | "debuff" | "stun" | "ice_hit" | "player_hit" | "critical_hit" | "status_apply" | "ice_intro" | "ice_death" | "boss_phase_transition" | "victory" | "defeat" | "heavy_attack" | "pierce" | "multi_hit" | "dot" | "counter" | "lifesteal" | "detect" | "regen" | "jackin_glitch" | "jackout_whiteout" | "room_flash" | "data_acquired";

export type StatusKind = "BUFF" | "BURN" | "DEBUFF" | "DOT" | "POISON" | "REGEN" | "SHIELD" | "STUN";

export type IceType = "black" | "construct" | "goliath" | "standard" | "ta_construct_prime" | "watchdog" | "wintermute";

export const EFFECTS: ReadonlyArray<EffectSpec> = [
  EFFECT_ATTACK,
  EFFECT_HEAL,
  EFFECT_SHIELD,
  EFFECT_BUFF,
  EFFECT_DEBUFF,
  EFFECT_STUN,
  EFFECT_ICE_HIT,
  EFFECT_PLAYER_HIT,
  EFFECT_CRITICAL_HIT,
  EFFECT_STATUS_APPLY,
  EFFECT_ICE_INTRO,
  EFFECT_ICE_DEATH,
  EFFECT_BOSS_PHASE_TRANSITION,
  EFFECT_VICTORY,
  EFFECT_DEFEAT,
  EFFECT_HEAVY_ATTACK,
  EFFECT_PIERCE,
  EFFECT_MULTI_HIT,
  EFFECT_DOT,
  EFFECT_COUNTER,
  EFFECT_LIFESTEAL,
  EFFECT_DETECT,
  EFFECT_REGEN,
  EFFECT_JACKIN_GLITCH,
  EFFECT_JACKOUT_WHITEOUT,
  EFFECT_ROOM_FLASH,
  EFFECT_DATA_ACQUIRED,
];

export interface EffectSpec {
  readonly kind: EffectKind;
  readonly category: string;
  readonly duration_ms: number;
  readonly duration_ticks: number;
  readonly color_hint: string;
  readonly payload: Readonly<Record<string, unknown>>;
}

export const EFFECT_ATTACK: {
  readonly kind: "attack";
  readonly category: "combat.skill";
  readonly duration_ms: 240;
  readonly duration_ticks: 15;
  readonly color_hint: "DAMAGE_COLOR";
  readonly payload: {
  readonly program_name: string;
  readonly damage: number;
};
};

export const EFFECT_HEAL: {
  readonly kind: "heal";
  readonly category: "combat.skill";
  readonly duration_ms: 320;
  readonly duration_ticks: 20;
  readonly color_hint: "HEAL_COLOR";
  readonly payload: {
  readonly amount: number;
};
};

export const EFFECT_SHIELD: {
  readonly kind: "shield";
  readonly category: "combat.skill";
  readonly duration_ms: 280;
  readonly duration_ticks: 18;
  readonly color_hint: "SHIELD_COLOR";
  readonly payload: {
  readonly target: "player" | "ice";
};
};

export const EFFECT_BUFF: {
  readonly kind: "buff";
  readonly category: "combat.skill";
  readonly duration_ms: 240;
  readonly duration_ticks: 15;
  readonly color_hint: "BUFF_COLOR";
  readonly payload: {
  readonly stat: string;
  readonly amount: number;
};
};

export const EFFECT_DEBUFF: {
  readonly kind: "debuff";
  readonly category: "combat.skill";
  readonly duration_ms: 240;
  readonly duration_ticks: 15;
  readonly color_hint: "DEBUFF_COLOR";
  readonly payload: {
  readonly stat: string;
  readonly amount: number;
};
};

export const EFFECT_STUN: {
  readonly kind: "stun";
  readonly category: "combat.skill";
  readonly duration_ms: 320;
  readonly duration_ticks: 20;
  readonly color_hint: "STUN_COLOR";
  readonly payload: {
  readonly target: "player" | "ice";
  readonly duration_turns: number;
};
};

export const EFFECT_ICE_HIT: {
  readonly kind: "ice_hit";
  readonly category: "combat.hit";
  readonly duration_ms: 160;
  readonly duration_ticks: 10;
  readonly color_hint: "DAMAGE_COLOR";
  readonly payload: {
  readonly damage: number;
};
};

export const EFFECT_PLAYER_HIT: {
  readonly kind: "player_hit";
  readonly category: "combat.hit";
  readonly duration_ms: 200;
  readonly duration_ticks: 13;
  readonly color_hint: "DAMAGE_COLOR";
  readonly payload: {
  readonly damage: number;
};
};

export const EFFECT_CRITICAL_HIT: {
  readonly kind: "critical_hit";
  readonly category: "combat.hit";
  readonly duration_ms: 320;
  readonly duration_ticks: 20;
  readonly color_hint: "CRIT_COLOR";
  readonly payload: {
  readonly damage: number;
  readonly is_player_attacker: boolean;
};
};

export const EFFECT_STATUS_APPLY: {
  readonly kind: "status_apply";
  readonly category: "status";
  readonly duration_ms: 240;
  readonly duration_ticks: 15;
  readonly color_hint: "DEFAULT_COLOR";
  readonly payload: {
  readonly status_kind: StatusKind;
  readonly target: "player" | "ice";
};
};

export const EFFECT_ICE_INTRO: {
  readonly kind: "ice_intro";
  readonly category: "cinematic";
  readonly duration_ms: 640;
  readonly duration_ticks: 40;
  readonly color_hint: "ICE_BREAK_COLOR";
  readonly payload: {
  readonly ice_type: IceType;
  readonly ice_name: string;
};
};

export const EFFECT_ICE_DEATH: {
  readonly kind: "ice_death";
  readonly category: "cinematic";
  readonly duration_ms: 640;
  readonly duration_ticks: 40;
  readonly color_hint: "ICE_BREAK_COLOR";
  readonly payload: {
  readonly ice_type: IceType;
  readonly ice_name: string;
};
};

export const EFFECT_BOSS_PHASE_TRANSITION: {
  readonly kind: "boss_phase_transition";
  readonly category: "cinematic";
  readonly duration_ms: 800;
  readonly duration_ticks: 50;
  readonly color_hint: "PHASE_COLOR_BY_INDEX";
  readonly payload: {
  readonly boss_phase: number;
  readonly previous_phase: number;
};
};

export const EFFECT_VICTORY: {
  readonly kind: "victory";
  readonly category: "outcome";
  readonly duration_ms: 800;
  readonly duration_ticks: 50;
  readonly color_hint: "GREEN_NEON";
  readonly payload: Record<string, never>;
};

export const EFFECT_DEFEAT: {
  readonly kind: "defeat";
  readonly category: "outcome";
  readonly duration_ms: 800;
  readonly duration_ticks: 50;
  readonly color_hint: "RED_BRIGHT";
  readonly payload: Record<string, never>;
};

export const EFFECT_HEAVY_ATTACK: {
  readonly kind: "heavy_attack";
  readonly category: "combat.skill";
  readonly duration_ms: 900;
  readonly duration_ticks: 57;
  readonly color_hint: "ORANGE";
  readonly payload: {
  readonly damage: number;
};
};

export const EFFECT_PIERCE: {
  readonly kind: "pierce";
  readonly category: "combat.skill";
  readonly duration_ms: 310;
  readonly duration_ticks: 20;
  readonly color_hint: "WARM";
  readonly payload: {
  readonly damage: number;
};
};

export const EFFECT_MULTI_HIT: {
  readonly kind: "multi_hit";
  readonly category: "combat.skill";
  readonly duration_ms: 290;
  readonly duration_ticks: 19;
  readonly color_hint: "DAMAGE_COLOR";
  readonly payload: {
  readonly hit_count: number;
  readonly total_damage: number;
};
};

export const EFFECT_DOT: {
  readonly kind: "dot";
  readonly category: "combat.skill";
  readonly duration_ms: 550;
  readonly duration_ticks: 35;
  readonly color_hint: "ICE_FADE_PURPLE";
  readonly payload: {
  readonly magnitude: number;
  readonly target: "player" | "ice";
};
};

export const EFFECT_COUNTER: {
  readonly kind: "counter";
  readonly category: "combat.skill";
  readonly duration_ms: 420;
  readonly duration_ticks: 27;
  readonly color_hint: "SHIELD_COLOR";
  readonly payload: {
  readonly damage: number;
};
};

export const EFFECT_LIFESTEAL: {
  readonly kind: "lifesteal";
  readonly category: "combat.skill";
  readonly duration_ms: 490;
  readonly duration_ticks: 31;
  readonly color_hint: "DAMAGE_COLOR";
  readonly payload: {
  readonly damage: number;
  readonly heal_amount: number;
};
};

export const EFFECT_DETECT: {
  readonly kind: "detect";
  readonly category: "combat.skill";
  readonly duration_ms: 550;
  readonly duration_ticks: 35;
  readonly color_hint: "SHIELD_COLOR";
  readonly payload: {
  readonly target: "player" | "ice";
};
};

export const EFFECT_REGEN: {
  readonly kind: "regen";
  readonly category: "combat.skill";
  readonly duration_ms: 450;
  readonly duration_ticks: 29;
  readonly color_hint: "ICE_GREEN_BRIGHT";
  readonly payload: {
  readonly amount: number;
};
};

export const EFFECT_JACKIN_GLITCH: {
  readonly kind: "jackin_glitch";
  readonly category: "matrix.dungeon";
  readonly duration_ms: 500;
  readonly duration_ticks: 32;
  readonly color_hint: "ICE_CYAN_DIM";
  readonly payload: Record<string, never>;
};

export const EFFECT_JACKOUT_WHITEOUT: {
  readonly kind: "jackout_whiteout";
  readonly category: "matrix.dungeon";
  readonly duration_ms: 400;
  readonly duration_ticks: 25;
  readonly color_hint: "HIT_FLASH_COLOR";
  readonly payload: Record<string, never>;
};

export const EFFECT_ROOM_FLASH: {
  readonly kind: "room_flash";
  readonly category: "matrix.dungeon";
  readonly duration_ms: 80;
  readonly duration_ticks: 5;
  readonly color_hint: "OLIVE";
  readonly payload: {
  readonly color_hint: string;
};
};

export const EFFECT_DATA_ACQUIRED: {
  readonly kind: "data_acquired";
  readonly category: "matrix.dungeon";
  readonly duration_ms: 500;
  readonly duration_ticks: 32;
  readonly color_hint: "TIER_GOLD";
  readonly payload: Record<string, never>;
};
