"""Combat subsystem (ADR-0003, ADR-0014, ADR-0018, ADR-0019, ADR-0147, ADR-0148, ADR-0149).

Phase 5: text-based combat model + simulator (developer/QA tool).
Phase 6+: full integration with the engine (animations, salvage, aftermath).
"""

from .boss_phase4 import (
    BOSS_INTRO,
    CONSTRUCT_MERGE_ATTACK_BONUS,
    CONSTRUCT_MERGE_DURATION_MS,
    CONSTRUCT_MERGE_HEAL_PCT,
    DEATH_TAUNTS,
    FAMILY_VOTE_COMPANION_BONUS,
    FAMILY_VOTE_DAMAGE,
    GLITCH_BURST_DURATION_MS,
    GLITCH_BURST_STATUS_COUNT,
    GROUND_SLAM_SHAKE_DURATION_MS,
    GROUND_SLAM_SHAKE_INTENSITY,
    GROUND_SLAM_STUN_MS,
    PERSONALITY_DRIFT_DURATION_MS,
    PERSONALITY_DRIFT_PCT,
    PHASE4_HP_THRESHOLD,
    BossIntroEnhancement,
    Phase4Mechanic,
    apply_boss_intro_enhancement,
    apply_construct_merge,
    apply_death_taunt,
    apply_family_vote,
    apply_glitch_burst,
    apply_ground_slam,
    apply_personality_drift,
    apply_phase4_mechanic,
    get_boss_intro,
    pick_death_taunt,
    should_trigger_phase4,
    trigger_phase4,
)
from .depth import (
    AGGRESSION_PROBABILITY,
    COUNTER_DAMAGE_MULTIPLIER,
    COUNTER_STUN_MS,
    COUNTER_WINDOW_MS,
    AggressionLevel,
    CompanionSkillId,
    DefenseProgram,
    apply_counter_attack,
    apply_shield_barrier,
    apply_wardrone,
    apply_wisp,
    counter_window_active_and_expired,
    dixie_choose_skill,
    dixie_use_skill,
    enemy_should_use_skill,
    is_counter_window_open,
    open_counter_window,
    tick_defense_durations,
    tick_defense_expiry,
)
from .intel_items import (
    ALARM_FLOOR,
    ALARM_REDUCER_DELTA,
    ALARM_REDUCER_PRICE,
    FACTION_RUMOR_FACTION,
    FACTION_RUMOR_PRICE,
    FACTION_RUMOR_PROBABILITY_BOOST,
    MISSION_HINT_PRICE,
    IntelItemId,
    apply_alarm_reducer,
    apply_faction_rumor,
    apply_intel_item,
    apply_mission_hint,
    get_intel_item_price,
)
from .multi_enemy import (
    ENCOUNTER_COUNT_BY_GRADE,
    all_alive_enemies,
    auto_attack_all_alive,
    cycle_target,
    encounter_count_for_grade,
)
from .registry import (
    IceRegistry,
    ProgramRegistry,
    build_default_player,
    build_ice_enemy,
)
from .salvage import (
    ALARM_HIGH_THRESHOLD,
    ALARM_MIN,
    ALARM_REDUCTION_PCT,
    CRED_ALARM_RELIEF,
    CRED_CREDITS,
    FRAG_YIELD,
    HEAL_MIN,
    HEAL_PCT,
    SalvageChoice,
    apply_salvage,
)
from .state import Combatant, CombatState, Skill, step_combat, use_skill

__all__ = [
    "AGGRESSION_PROBABILITY",
    "ALARM_HIGH_THRESHOLD",
    "ALARM_MIN",
    "ALARM_REDUCTION_PCT",
    "AggressionLevel",
    "BOSS_INTRO",
    "COUNTER_DAMAGE_MULTIPLIER",
    "COUNTER_STUN_MS",
    "COUNTER_WINDOW_MS",
    "CRED_ALARM_RELIEF",
    "CRED_CREDITS",
    "CONSTRUCT_MERGE_ATTACK_BONUS",
    "CONSTRUCT_MERGE_DURATION_MS",
    "CONSTRUCT_MERGE_HEAL_PCT",
    "Combatant",
    "CombatState",
    "CompanionSkillId",
    "DEATH_TAUNTS",
    "DefenseProgram",
    "FAMILY_VOTE_COMPANION_BONUS",
    "FAMILY_VOTE_DAMAGE",
    "FRAG_YIELD",
    "GLITCH_BURST_DURATION_MS",
    "GLITCH_BURST_STATUS_COUNT",
    "GROUND_SLAM_SHAKE_DURATION_MS",
    "GROUND_SLAM_SHAKE_INTENSITY",
    "GROUND_SLAM_STUN_MS",
    "HEAL_MIN",
    "HEAL_PCT",
    "IceRegistry",
    "PERSONALITY_DRIFT_DURATION_MS",
    "PERSONALITY_DRIFT_PCT",
    "PHASE4_HP_THRESHOLD",
    "ProgramRegistry",
    "SalvageChoice",
    "Skill",
    "BossIntroEnhancement",
    "Phase4Mechanic",
    "apply_boss_intro_enhancement",
    "apply_construct_merge",
    "apply_counter_attack",
    "apply_death_taunt",
    "apply_family_vote",
    "apply_glitch_burst",
    "apply_ground_slam",
    "apply_personality_drift",
    "apply_phase4_mechanic",
    "apply_salvage",
    "apply_shield_barrier",
    "apply_wardrone",
    "apply_wisp",
    "build_default_player",
    "build_ice_enemy",
    "counter_window_active_and_expired",
    "dixie_choose_skill",
    "dixie_use_skill",
    "enemy_should_use_skill",
    "get_boss_intro",
    "is_counter_window_open",
    "open_counter_window",
    "pick_death_taunt",
    "should_trigger_phase4",
    "step_combat",
    "tick_defense_durations",
    "tick_defense_expiry",
    "trigger_phase4",
    "use_skill",
    "ALARM_FLOOR",
    "ALARM_REDUCER_DELTA",
    "ALARM_REDUCER_PRICE",
    "FACTION_RUMOR_FACTION",
    "FACTION_RUMOR_PRICE",
    "FACTION_RUMOR_PROBABILITY_BOOST",
    "IntelItemId",
    "MISSION_HINT_PRICE",
    "apply_alarm_reducer",
    "apply_faction_rumor",
    "apply_intel_item",
    "apply_mission_hint",
    "get_intel_item_price",
    "ENCOUNTER_COUNT_BY_GRADE",
    "all_alive_enemies",
    "auto_attack_all_alive",
    "cycle_target",
    "encounter_count_for_grade",
]


def enrich_mission_registry(
    mission_id: str,
    base_data: dict[str, object],
) -> dict[str, object]:
    """Wire ADR-0166/0167 registry fields into a missions.json entry.

    Looks up ``mission_id`` in Arc6 + Expansion registries. If matched,
    merges registry-only fields (registry_description, registry_story_intro,
    registry_primary_ice, registry_source) into ``base_data`` without
    overriding existing keys. If not matched, returns ``base_data`` unchanged.
    """
    from .arc6 import enrich_arc6_mission
    from .mission_expansion import enrich_expansion_mission

    enriched = enrich_arc6_mission(mission_id, base_data)
    if enriched is None:
        enriched = enrich_expansion_mission(mission_id, base_data)
    return enriched if enriched is not None else dict(base_data)
